logging:
  level:
    ru:
      yandex: TRACE
    org:
      springframework:
        jdbc:
          core: TRACE
        web: TRACE
      zalando:
        logbook: TRACE
server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:file:./db/filmorate
    driverClassName: org.h2.Driver
    username: sa
    password: password
  sql:
    init:
      mode: always